services:
  db:
    image: postgres:16
    container_name: deploy-db-1
    restart: unless-stopped
    environment:
      POSTGRES_DB: mycloud
      POSTGRES_USER: mycloud
      POSTGRES_PASSWORD: mycloud
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycloud -d mycloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: deploy-backend-1
    build:
      # Контекст — корень репозитория (frontend/, backend/, wheelhouse/)
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: mycloud.settings.prod
      DATABASE_URL: postgres://mycloud:mycloud@db:5432/mycloud
    volumes:
      - webroot:/usr/share/nginx/html
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport os, django\nos.environ.setdefault('DJANGO_SETTINGS_MODULE', os.getenv('DJANGO_SETTINGS_MODULE','mycloud.settings.prod'))\ndjango.setup(); from django.db import connections; connections['default'].cursor().execute('SELECT 1'); print('OK')\nPY",
        ]
      interval: 20s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.27-alpine
    container_name: deploy-nginx-1
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s 

volumes:
  pgdata:
  webroot:
