name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compose-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker & Compose versions
        run: |
          docker --version
          docker compose version

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images via compose
        working-directory: deploy
        run: docker compose build

      - name: Start DB
        working-directory: deploy
        run: |
          docker compose up -d db
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if docker compose exec -T db pg_isready -U postgres; then
              break
            fi
            sleep 2
          done

      - name: Run migrations (inside backend container)
        working-directory: deploy
        run: docker compose run --rm backend python manage.py migrate --noinput

      - name: Run tests (inside backend container)
        working-directory: deploy
        run: docker compose run --rm backend bash -lc 'python manage.py test accounts.tests.test_auth storageapp.tests.test_files accounts.tests.test_admin_api -v 2'

      - name: Compose down
        if: always()
        working-directory: deploy
        run: docker compose down -v
